services:
  db:
    image: postgres:16-alpine
    container_name: comet-postgres
    environment:
      POSTGRES_DB: cometlab
      POSTGRES_USER: cometuser
      POSTGRES_PASSWORD: cometpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cometuser -d cometlab"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: comet-backend
    environment:
      DATABASE_URL: postgresql://cometuser:cometpass123@db:5432/cometlab
      UPLOAD_DIR: /app/uploads
      FRONTEND_ORIGIN: http://localhost:5173
      SAMPLE_PROPAGATION_DAYS: 365
      SECRET_KEY: your-secret-key-change-in-production-please-use-strong-random-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 43200
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    container_name: comet-frontend
    environment:
      VITE_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
